dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: eFTaXlBPSNrrpzlJeZ6i70sehyy24Kkrgp7qMy2D1AkASExDnoSBZNZ3Q06qSUq+vTlL+imgISR/EHAg5tkm1zgI/W0k0V3bkdLG3jR4LKwiLnfo+DdrdfGsutCQlOkM9S5QbPIIPvCE58j6BFUeqzL2lxPAmMvnQvgBCXKRKWiNL0d9jLWcFbjFVtIf/8pHhWVywaHnLwJKV+Z1fMhYmZqHwo0SNW1BMoegSUZTkWm6RfwGVOzSGHaFetsio3ZQJZwEaMN+icdVC4yoeghsOVZ+UnaQk1oeuywOXLgPgKHZrQQ3pE5ttb/YjojpcshsSdg8Dw1c8s27kki8RiEa+giodG7tIaS2ZO2pHh47czUgvUsycDjEAR5vZu0N2hUI/ZtZtFJTfHDHXsvSKbtoWlacwwENd1nqTqp9NKPTkz/yQbBikM3jj7nzIenGCYG8OZTy2jeFPnFKHBRaLTPWyifPR/FInuPnSJRg2BduiKCo7DqV8cFuYd9jKXq8MudZPTC1+mZvCp2dX/OE7Reas1n5fpHGxDFh7W92Iuma2ZQ0h1mcG7nAbvAT0yMHaIj4TGaWoSSl3CKLEi05bMmqq5Gcd995ZV7lxlB02hcn8aBZLFIyY5PzG54EYNFyVYS2TJbl+J2h8kPer0ThCAQT75DZDsVnkArRxg8BlYVH9Fc=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_thermistor.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-thermistor
  --library_location .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
